MOUSEKEY_ENABLE = yes    # Mouse keys
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_ENABLE = no
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes

MOUSEKEY_ENABLE = no
 EXTRAKEY_ENABLE = no
 LTO_ENABLE = yes
